const path = require('path');
process.chdir(path.join(__dirname, '..', '..', '..'));
const Database = require('better-sqlite3');
const dbPath = process.argv[2] || path.join(process.env.APPDATA, 'seer-tactics', 'db', 'seer.db');
console.log('Opening:', dbPath);
const db = new Database(dbPath, { readonly: true });
console.log('sprites:', db.prepare('SELECT COUNT(*) as c FROM sprites').get().c);
console.log('skills:', db.prepare('SELECT COUNT(*) as c FROM skills').get().c);
console.log('tables:', db.prepare("SELECT name FROM sqlite_master WHERE type='table'").all().map(r => r.name).join(', '));
const cols = db.prepare("PRAGMA table_info(sprites)").all().map(r => r.name);
console.log('sprite columns:', cols.join(', '));
const sample = db.prepare('SELECT id, name_zh, cn_id, types, playstyle FROM sprites LIMIT 3').all();
console.log('sample:', JSON.stringify(sample, null, 2));
db.close();
